server:
  port: 8070

spring:
  application:
    name: comments
  datasource:
    url: jdbc:postgresql://localhost:5432/licenta1
    username: postgres
    password: a2001
    driver-class-name: org.postgresql.Driver
  servlet:
    cors:
      enabled: true
      allowed-origins: "http://localhost:3000"  # Replace with your frontend application URL
      allowed-methods: GET, POST, PUT, DELETE
      allowed-headers: Content-Type, Authorization

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  main:
    web-application-type: servlet
  profiles:
    active: default

eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

application:
  config:
    users-url: http://localhost:8222/api/users/

management:
  tracing:
    sampling:
      probability: 1.0