eureka:
  client:
    register-with-eureka: false

server:
  port: 8222

spring:
  application:
    name: gateway
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - http://localhost:3000
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
            allowedHeaders:
              - Content-Type
              - Authorization
            allowCredentials: true
      discovery:
        locator:
          enabled: true
      routes:
        - id: licenta
          uri: http://localhost:8080
          predicates:
            - Path=/api/users/**
        - id: licenta
          uri: http://localhost:8080
          predicates:
            - Path=/api/avatars/**
        - id: licenta
          uri: http://localhost:8080
          predicates:
            - Path=/api/posts/**
        - id: licenta
          uri: http://localhost:8080
          predicates:
            - Path=/api/likes/**
        - id: comments
          uri: http://localhost:8070
          predicates:
            - Path=/api/comments/**
        - id: challenges
          uri: http://localhost:8090
          predicates:
            - Path=/api/challenges/**

management:
  tracing:
    sampling:
      probability: 1.0