server:
  port: 8080
aws:
  access:
    key:
      id: AKIA5W5BG4B5ZUTTELP3
  secret:
    access:
      key: 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
  s3:
    region: eu-north-1
    bucket:
      name: licenta1
spring:
  application:
    name: licenta
  datasource:
    url: jdbc:postgresql://localhost:5432/licenta1
    username: postgres
    password: a2001
    driver-class-name: org.postgresql.Driver
  servlet:
    multipart:
      max-file-size: -1
      max-request-size: -1
  profiles:
    active: default

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  main:
    web-application-type: servlet

eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

management:
  tracing:
    sampling:
      probability: 1.0
