#services:
#  postgres:
#    container_name: licenta1
#    image: postgres:latest
#    environment:
#      POSTGRES_USER: postgres
#      POSTGRES_PASSWORD: mysecretpassword
#      PGDATA: /data/postgres
#    volumes:
#      - postgres-db:/data/postgres
#    ports:
#      - "5432:5432"
#
#
#volumes:
#  postgres-db:
#    driver: local
services:
  zipkin:
    container_name: zipkin
    image: openzipkin/zipkin
    ports:
      - "9411:9411"
    networks:
      - zipkin

networks:
  zipkin:
    driver: bridge

